load("@gerbil_bazel//gerbil:defs.bzl", "gerbil_project_compile")

package(default_visibility = ["//visibility:private"])

exports_files([
    "build.ss",
    "gerbil.pkg",
])

filegroup(
    name = "project_sources",
    srcs = ["gerbil.pkg"] + glob([
        "src/**/*.inc",
        "src/**/*.ss",
    ]),
)

gerbil_project_compile(
    name = "gerbil_utils_package",
    srcs = ["@gerbil_utils_sources//:sources"],
    build_script = "@gerbil_utils_sources//:build_script",
    process_guard = True,
    require_library_output = True,
    source_resolution_receipts = [
        "@gerbil_utils_sources//:source_resolution_receipt",
    ],
)

gerbil_project_compile(
    name = "gerbil_poo_package",
    srcs = ["@gerbil_poo_sources//:sources"],
    build_script = "@gerbil_poo_sources//:build_script",
    process_guard = True,
    require_library_output = True,
    source_resolution_receipts = [
        "@gerbil_poo_sources//:source_resolution_receipt",
    ],
    deps = [":gerbil_utils_package"],
)

gerbil_project_compile(
    name = "compile",
    srcs = [":project_sources"],
    args = ["compile"],
    build_script = ":build.ss",
    deps = [":gerbil_poo_package"],
    visibility = ["//visibility:public"],
)
