((scenarioKind . native-gerbil-build)
 (attemptCount . 1)
 (maxNanoseconds . 5000000000)
 (targetNanoseconds . 3000000000)
 (executor . std/make)
 (importModel . gerbil/module-context-import)
 (algorithm . "root-only O(V+E) traversal with identity visited set")
 (packageIdentity . asp-native-import-public-closure-fixture)
 (publicEntry . "c.ss")
 (expectedTargets "a.ss" "b.ss" "c.ss")
 (excludedTarget . "unrelated.ss")
 (cacheOwner . GERBIL_PATH)
 (packageOutputPrecondition . absent)
 (pooResponsibility . public-entry-module-declaration))
