((scenarioKind . native-gerbil-build)
 (attemptCount . 5)
 (executor . std/make)
 (importModel . gerbil/module-context-import)
 (packageIdentity . asp-native-import-public-closure-fixture)
 (publicEntry . "c.ss")
 (directRootTargets "c.ss")
 (expectedTargets "fixture-prelude.ss" "syntax-helper.ss" "a.ss" "b.ss" "c.ss")
 (compiledTargets "syntax-helper.ss" "fixture-prelude.ss" "a.ss" "b.ss" "c.ss")
 (projectionLanes source-context compiled-interface)
 (localPrelude . "fixture-prelude.ss")
 (excludedTarget . "unrelated.ss")
 (pooResponsibility . public-entry-module-declaration)
 (expectedOutcome
  . "modules returns the declared root; source and compiled public-entry projection both include the local prelude and phase imports"))
