((scenarioKind . native-gerbil-build)
 (attemptCount . 2)
 (executor . std/make)
 (importModel . gerbil/module-context-import)
 (algorithm . "root-only O(V+E) traversal with identity visited set")
 (packageIdentity . asp-native-import-public-closure-fixture)
 (publicEntry . "c.ss")
 (directRootTargets "c.ss")
 (expectedTargets "a.ss" "b.ss" "c.ss")
 (excludedTarget . "unrelated.ss")
 (cacheOwner . GERBIL_PATH)
 (packageOutputPrecondition . absent)
 (pooResponsibility . public-entry-module-declaration)
 (expectedOutcome
  . "modules returns the declared root while public-entry-modules returns exactly its native import closure"))
