((scenarioKind . native-package-spec-ab)
 (attemptCount . 3)
 (executor . std/make)
 (targetCount . 1)
 (sourceTarget . "probe.ss")
 (runnerLanguage . gerbil-scheme)
 (shellRunner . #f)
 (nativeBuild . "native-build.ss")
 (candidateBuild . "asp-build.ss")
 (outputIsolation . identical-empty-images)
 (warmCompileCount . 0)
 (maxProjectionOverheadSeconds . 3)
 (targetRationale
  . "The same macro-heavy target and std/make executor isolate PackageSpec projection and process-loading overhead from native currentness work.")
 (measurementPhases scenario-start spec-process-start spec-process-returned
                    compile-process-start compile-process-returned)
 (requiredEvidence upstream-revision cold-seconds warm-samples warm-p50 compile-counts))
