;;; -*- Gerbil -*-
(import :std/test
        (only-in :asp-gerbil-scheme/src/parser/package read-project-package)
        :asp-gerbil-scheme/src/extensions/facade
        :asp-gerbil-scheme/src/parser/facade
        :asp-gerbil-scheme/src/protocol/json
        :std/srfi/13)
(export parser-test-part-1)

;; : (-> Json (List JsonValue))
(def (syntax-relation-projection-values row)
  (map (lambda (key) (hash-get row key))
       '(kind name owner path start end phase context structuralPath)))

;; : (-> (List (List Json)) (List (List (List JsonValue))))
(def (syntax-relation-projections-values projections)
  (map (lambda (rows) (map syntax-relation-projection-values rows))
       projections))

;; : (-> Selector Relpath Boolean )
(def (selector-owner? selector path)
  (and (string? selector)
       (string-prefix? (string-append path ":") selector)))

;; : (-> (List CallFact) Argument FindCallWithArgument )
(def (find-call-with-argument calls argument)
  (find (lambda (call)
          (equal? (call-fact-arguments call) [argument]))
        calls))
;; : (-> (List QualityFacet) QualityFacet Boolean )
(def (quality-facet-member? facets facet)
  (not (not (member facet facets))))
;; : (-> (List MacroFact) String MacroFact )
(def (find-macro facts name)
  (find (lambda (fact)
          (equal? (macro-fact-name fact) name))
        facts))
;; : (-> (List HigherOrderFact) String String String (List HigherOrderFact) )
(def (find-higher-order facts name role caller)
  (find (lambda (fact)
          (and (equal? (higher-order-fact-name fact) name)
               (equal? (higher-order-fact-role fact) role)
               (equal? (or (higher-order-fact-caller fact) "") caller)))
        facts))
;; : (-> (List ControlFlowFact) String String String (List ControlFlowFact) )
(def (find-control-flow facts name role caller)
  (find (lambda (fact)
          (and (equal? (control-flow-fact-name fact) name)
               (equal? (control-flow-fact-role fact) role)
               (equal? (or (control-flow-fact-caller fact) "") caller)))
        facts))
;; : (-> (List TypedContractFact) String (List TypedContractFact) )
(def (find-typed-contract facts name)
  (find (lambda (fact)
          (equal? (typed-contract-fact-definition-name fact) name))
        facts))
;; : (-> (List PredicateFamilyFact) String PredicateFamilyFact )
(def (find-predicate-family facts subject)
  (find (lambda (fact)
          (equal? (predicate-family-fact-subject fact) subject))
        facts))
;; : (-> (List FieldAccessPatternFact) String FieldAccessPatternFact )
(def (find-field-access-pattern facts field-key)
  (find (lambda (fact)
          (equal? (field-access-pattern-fact-field-key fact) field-key))
        facts))
;; : (-> (List BooleanConditionFact) String BooleanConditionFact )
(def (find-boolean-condition facts caller)
  (find (lambda (fact)
          (equal? (boolean-condition-fact-caller fact) caller))
        facts))
;; : (-> (List LoopDriverFact) String LoopDriverFact )
(def (find-loop-driver facts caller)
  (find (lambda (fact)
          (equal? (loop-driver-fact-caller fact) caller))
        facts))
;; : (-> (List FunctionQualityProfile) String FunctionQualityProfile )
(def (find-function-quality-profile profiles name)
  (find (lambda (profile)
          (equal? (function-quality-profile-name profile) name))
        profiles))
;; : (-> (List PooFormFact) String PooFormFact )
(def (find-poo-form facts name)
  (find (lambda (fact)
          (equal? (poo-form-fact-name fact) name))
        facts))
;; : (-> (List PooFormFact) String String PooFormFact )
(def (find-poo-form-role facts name role)
  (find (lambda (fact)
          (and (equal? (poo-form-fact-name fact) name)
               (equal? (poo-form-fact-role fact) role)))
        facts))
;; : (-> SourceFile String TopForm)
(def (find-syntax-owner-form file owner)
  (find (lambda (form)
          (equal? (syntax-ast-owner (top-form-syntax-ast form)) owner))
        (source-file-forms file)))

;; : (-> TopForm Symbol Symbol (List SyntaxRelation))
(def (syntax-owner-relations form name context)
  (filter (lambda (relation)
            (and (eq? (syntax-relation-name relation) name)
                 (eq? (syntax-relation-context relation) context)))
          (syntax-ast-relations (top-form-syntax-ast form))))
;; ParsedData
;; : (-> String EnsureDir )
(def (ensure-dir path)
  (with-catch
   (lambda (_) #f)
   (lambda () (create-directory path))))
;; : (-> String SourceLine Unit )
(def (write-text path text)
  (with-catch
   (lambda (_) #f)
   (lambda () (delete-file path)))
  (call-with-output-file path
    (lambda (port) (display text port))))
;; TestSuite
(def parser-test-part-1
  (test-suite "gerbil scheme harness parser part 1"
    (test-case "native reader captures package and definitions"
          (let* ((root (path-normalize "."))
                 (file (parse-source-file root "t/fixtures/sample.ss")))
            (check (source-file-package file) => "sample")
            (check (map definition-name (source-file-definitions file))
                   => ["answer" "make-answer"])
            (check (map definition-formals (source-file-definitions file))
                   => ['() '()])
            (check (map definition-arity (source-file-definitions file))
                   => [0 0])
            (check (map top-form-head (source-file-forms file))
                   => ["import" "export" "def" "def"])
            (check (map top-form-kind (source-file-forms file))
                   => ["import" "export" "definition" "definition"])
            (check (selector-owner? (top-form-selector (car (source-file-forms file)))
                                    "t/fixtures/sample.ss")
                   => #t)
            (check (>= (source-file-line-count file) 12) => #t)))
    (test-case "native reader classifies FFI declarations as declarative top forms"
          (let* ((root ".run/parser-declarative-top-form")
                 (src (string-append root "/src"))
                 (owner (string-append src "/ffi")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir owner)
            (write-text (string-append owner "/core.ss")
                        ";;; -*- Gerbil -*-\n(declare\n  (block)\n  (standard-bindings))\n(def (named) #t)\n")
            (let (file (parse-source-file root "src/ffi/core.ss"))
              (check (map top-form-head (source-file-forms file))
                     => ["declare" "def"])
              (check (map top-form-kind (source-file-forms file))
                     => ["declarative" "definition"])
              (check (map call-fact-callee (source-file-calls file))
                     => []))))
    (test-case "native syntax AST preserves phase, context, source, and deterministic projection"
          (let* ((root ".run/parser-native-syntax-ast")
                 (src (string-append root "/src"))
                 (path (string-append src "/macros.ss")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/native-syntax)\n")
            (write-text
             path
             (string-append
              "(defrules emitted-helper () ((_ value) value))\n"
              "(defrules declarative-public () ((_ value) (emitted-helper value)))\n"
              "(defsyntax (procedural-public stx)\n"
              "  (syntax-case stx () ((_ value) (syntax (emitted-helper value)))))\n"
              "(defsyntax identifier-public\n"
              "  (identifier-rules (id (emitted-helper id))))\n"
              "(defsyntax (quoted-only stx)\n"
              "  (let ((datum '(emitted-helper 1)))\n"
              "    (syntax-case stx () ((_ ) (syntax datum)))))\n"
              "(defsyntax (quasi-public stx)\n"
              "  (quasisyntax (emitted-helper (unsyntax (compute stx)))))\n"))
            (let* ((file (parse-source-file root "src/macros.ss"))
                   (again (parse-source-file root "src/macros.ss"))
                   (declarative (find-syntax-owner-form file "declarative-public"))
                   (procedural (find-syntax-owner-form file "procedural-public"))
                   (identifier (find-syntax-owner-form file "identifier-public"))
                   (quoted (find-syntax-owner-form file "quoted-only"))
                   (quasi (find-syntax-owner-form file "quasi-public"))
                   (quasi-helper (car (syntax-owner-relations
                                       quasi 'emitted-helper
                                       'quasisyntax-template)))
                   (quasi-compute (car (syntax-owner-relations
                                        quasi 'compute 'transformer))))
              (check (map (lambda (form)
                            (syntax-ast-version (top-form-syntax-ast form)))
                          (source-file-forms file))
                     => (make-list 6 "gerbil-native-syntax-relations.v2"))
              (check (syntax-ast-template-callees
                      (top-form-syntax-ast declarative))
                     => ["emitted-helper"])
              (check (syntax-ast-template-callees
                      (top-form-syntax-ast procedural))
                     => ["emitted-helper"])
              (check (syntax-ast-template-callees
                      (top-form-syntax-ast identifier))
                     => ["emitted-helper"])
              (check (syntax-ast-template-callees
                      (top-form-syntax-ast quoted))
                     => [])
              (check (syntax-relation-phase quasi-helper) => 0)
              (check (syntax-relation-phase quasi-compute) => 1)
              (check (> (syntax-relation-start quasi-helper) 0) => #t)
              (check (pair? (syntax-relation-structural-path quasi-helper)) => #t)
              (check (syntax-relation-projections-values
                      (map (lambda (form)
                             (syntax-ast-relation-projection
                              (top-form-syntax-ast form)))
                           (source-file-forms file)))
                     => (syntax-relation-projections-values
                         (map (lambda (form)
                                (syntax-ast-relation-projection
                                 (top-form-syntax-ast form)))
                              (source-file-forms again)))))))
    (test-case "package metadata does not project or load external policy config"
          (let* ((root ".run/parser-modularity-policy")
                 (policy-dir (string-append root "/policy"))
                 (config-path (string-append policy-dir "/modularity.ss")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir policy-dir)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/parser-policy\n  policy: ((modularity-policy config: \"policy/modularity.ss\" max-source-lines: 700)))\n")
            (write-text config-path
                        "(modularity-policy max-test-lines: 1000 min-test-definitions: 2 disabled-rules: (\"GERBIL-SCHEME-MOD-R007\") explanation: \"Large generated replay tests stay package-local while policy config remains out of the test owner.\")\n")
            (let* ((package (read-project-package root))
                   (fields (hash-get (project-package-json package) 'fields)))
              (check (project-package-name package) => "sample/parser-policy")
              (check (project-package-source-scope package) => #f)
              (check (hash-keys fields) => ['packageManager])
              ;; Invalid external data cannot affect package reading.
              (write-text config-path "(")
              (let ((again (project-package-json (read-project-package root)))
                    (expected (project-package-json package)))
                (check (hash-get again 'path) => (hash-get expected 'path))
                (check (hash-get again 'name) => (hash-get expected 'name))
                (check (hash-get again 'dependencies)
                       => (hash-get expected 'dependencies))
                (check (hash-get (hash-get again 'fields) 'packageManager)
                       => (hash-get (hash-get expected 'fields)
                                    'packageManager))))))
    (test-case "collect-source-scope keeps named owners despite package exclusions"
          (let* ((root ".run/parser-changed-project-files")
                 (src (string-append root "/src"))
                 (generated (string-append root "/src/generated")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir generated)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/parser-changed\n  policy: ((source-scope roots: (\"src\") exclude-directories: (\"generated\"))))\n")
            (write-text (string-append src "/changed.ss")
                        ";;; -*- Gerbil -*-\n(def (changed) #t)\n")
            (write-text (string-append src "/unchanged.ss")
                        ";;; -*- Gerbil -*-\n(def (unchanged) #t)\n")
            (write-text (string-append generated "/ignored.ss")
                        ";;; -*- Gerbil -*-\n(def (ignored) #t)\n")
            (write-text (string-append root "/README.md")
                        "not Gerbil source\n")
            (let* ((index
                    (collect-source-scope
                     root
                     ["src/changed.ss"
                      "src/generated/ignored.ss"
                      "src/missing.ss"
                      "README.md"]))
                   (files (project-index-files index)))
              (check (map source-file-path files)
                     => ["src/changed.ss" "src/generated/ignored.ss"])
              (check (map definition-name (project-definitions index))
                     => ["changed" "ignored"]))))
    (test-case "collect-test-source-scope deduplicates shared import closure"
          (let* ((root ".run/parser-test-source-scope-dedup")
                 (src (string-append root "/src"))
                 (tests (string-append root "/t")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir tests)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/parser-test-scope\n  policy: ((source-scope roots: (\"src\"))))\n")
            (write-text (string-append src "/core.ss")
                        ";;; -*- Gerbil -*-\n(export shared)\n(def (shared value) value)\n")
            (write-text (string-append tests "/a-test.ss")
                        ";;; -*- Gerbil -*-\n(import :core)\n(def (a) (shared 1))\n")
            (write-text (string-append tests "/b-test.ss")
                        ";;; -*- Gerbil -*-\n(import :core)\n(def (b) (shared 2))\n")
            (let* ((index
                    (collect-test-source-scope
                     root
                     ["t/a-test.ss" "t/b-test.ss" "src/core.ss"]))
                   (files (map source-file-path
                               (project-index-files index))))
              (check files => ["src/core.ss" "t/a-test.ss" "t/b-test.ss"])
              (check (length files) => 3))))
    (test-case "native reader captures definition formals"
          (let* ((root (path-normalize "."))
                 (file (parse-source-file root "t/fixtures/formals.ss")))
            (check (map definition-name (source-file-definitions file))
                   => ["sum-two" "collect"])
            (check (map definition-formals (source-file-definitions file))
                   => [["x" "y"] ["xs"]])
            (check (map definition-arity (source-file-definitions file))
                   => [2 1])))
    (test-case "native reader captures call facts"
          (let* ((root (path-normalize "."))
                 (file (parse-source-file root "t/fixtures/formals.ss"))
                 (calls (source-file-calls file)))
            (check (map call-fact-callee calls) => ["+"])
            (check (map call-fact-arity calls) => [2])
            (check (map call-fact-arguments calls) => [["x" "y"]])
            (check (map call-fact-argument-types calls) => [[#f #f]])
            (check (map call-fact-caller calls) => ["sum-two"])
            (check (map (lambda (selector)
                          (selector-owner? selector "t/fixtures/formals.ss"))
                        (map call-fact-selector calls))
                   => [#t])))
    (test-case "native reader preserves call order within one form"
          (let* ((root ".run/parser-call-order")
                 (src (string-append root "/src")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (write-text
             (string-append src "/calls.ss")
             ";;; -*- Gerbil -*-\n(def (ordered value)\n  (first value)\n  (second value))\n")
            (let* ((file (parse-source-file root "src/calls.ss"))
                   (calls
                    (filter (lambda (call)
                              (equal? (call-fact-caller call) "ordered"))
                            (source-file-calls file))))
              (check (map call-fact-callee calls)
                     => ["first" "second"]))))
    (test-case "native reader captures top-level value binding facts"
          (let* ((root ".run/parser-top-level-value-binding")
                 (src (string-append root "/src")))
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (write-text (string-append src "/cache.ss")
                        ";;; -*- Gerbil -*-\n(def +literal-cache-version+ \"cache.v1\")\n(def +derived-cache-version+ +release-version+)\n(def (run value)\n  value)\n")
            (let* ((file (parse-source-file root "src/cache.ss"))
                   (bindings
                    (filter (lambda (binding)
                              (equal? (binding-fact-scope binding)
                                      "top-level"))
                            (source-file-bindings file))))
              (check (map binding-fact-name bindings)
                     => ["+literal-cache-version+"
                         "+derived-cache-version+"])
              (check (map binding-fact-kind bindings)
                     => ["def" "def"])
              (check (map binding-fact-value-type bindings)
                     => ["string" #f])
              (check (map (lambda (selector)
                            (selector-owner? selector "src/cache.ss"))
                          (map binding-fact-selector bindings))
                     => [#t #t]))))))
