((scenarioKind . native-gerbil-build)
 (executor . std/make)
 (driver . gerbil-build)
 (buildCores . 8)
 (changedSource . "a.ss")
 (firstBuildTargets "a" "b" "c")
 (secondBuildTargets)
 (cacheOwner . GERBIL_PATH)
 (pooResponsibility . transitive-extra-input-projection))
