;;; -*- Gerbil -*-
;;; gerbil scheme harness agent build policy.

(import :gerbil/gambit
        :std/test
        :asp-gerbil-scheme/src/parser/facade
        :asp-gerbil-scheme/src/policy/facade
        :asp-gerbil-scheme/src/types/facade
        (only-in "./agent-build-canonical-acceptance-test"
                 agent-build-canonical-acceptance-policy-test)
        "./fixtures")
(export agent-build-policy-test)

;; PolicyTest
(def agent-build-runtime-policy-test
  (test-suite "gerbil scheme harness agent build runtime policy"
    (test-case "agent policy rejects package build CLI routing"
          (let ((root ".run/policy-package-build-routing"))
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-routing)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :clan/base)\n(def (write-wrapper out)\n  (display \"if [ \\\"${1:-}\\\" = search ] && [ \\\"${2:-}\\\" = pattern ]; then\\n\" out))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-019" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (type-finding-selector finding) => "build.ss:4-4")
              (check (hash-get (type-finding-details finding) 'kind)
                     => "package-build-responsibility"))))
    (test-case "agent policy rejects package build wrapper definitions"
          (let ((root ".run/policy-package-build-wrapper-definition"))
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-wrapper)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :clan/base)\n(def (write-native-link-wrapper build-prefix)\n  build-prefix)\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-019" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (type-finding-selector finding) => "build.ss:3-4")
              (check (hash-get (type-finding-details finding) 'kind)
                     => "package-build-wrapper-definition"))))
    (test-case "agent policy rejects compiler execution under a global lock"
          (let* ((root ".run/policy-build-runtime-global-lock-compile")
                 (src (string-append root "/src"))
                 (support (string-append src "/build-api")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-lock)\n")
            (write-text
             (string-append support "/scheduler.ss")
             ";;; -*- Gerbil -*-\n(def (compile-package! lock spec)\n  (with-lock lock\n    (lambda ()\n      (make spec))))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding) 'kind)
                               "build-runtime-global-lock-compile"))
                     (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                  findings)))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'caller) => "compile-package!")
              (check (hash-get details 'lockCallee) => "with-lock")
              (check (hash-get details 'compileCallee) => "make"))))
    (test-case "agent policy accepts a short state lock before compilation"
          (let* ((root ".run/policy-build-runtime-short-lock")
                 (src (string-append root "/src"))
                 (support (string-append src "/build-api")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-short-lock)\n")
            (write-text
             (string-append support "/scheduler.ss")
             ";;; -*- Gerbil -*-\n(def (transition-ready! lock table)\n  (with-lock lock (lambda () (hash-put! table 'ready #t))))\n(def (compile-package! spec)\n  (make spec))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding) 'kind)
                               "build-runtime-global-lock-compile"))
                     (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                  findings))))
              (check matching => []))))
    (test-case "agent policy rejects a serializing shadow module scheduler"
          (let* ((root ".run/policy-build-runtime-shadow-scheduler")
                 (src (string-append root "/src"))
                 (support (string-append src "/build-api")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-shadow-scheduler)\n")
            (write-text
             (string-append support "/scheduler.ss")
             ";;; -*- Gerbil -*-\n(def (import/mx lock module)\n  (with-lock lock (lambda () (import-module module))))\n(def (wait-for dependency)\n  (completion-wait! dependency))\n(def (coordinate! lock module dependency work)\n  (wait-for dependency)\n  (channel-put work (import/mx lock module)))\n(def (run-scheduler!)\n  (let (work (make-channel))\n    (channel-close work)))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding) 'kind)
                               "build-runtime-shadow-scheduler"))
                     (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                  findings)))
                   (details (type-finding-details (car matching))))
              (check (length matching) => 1)
              (check (string? (hash-get details 'lockSelector)) => #t)
              (check (string? (hash-get details 'dependencyWaitSelector)) => #t)
              (check (string? (hash-get details 'workChannelSelector)) => #t))))
    (test-case "agent policy accepts upstream native provider build ownership"
          (let* ((root ".run/policy-build-runtime-upstream-native")
                 (src (string-append root "/src"))
                 (support (string-append src "/build-api")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-upstream-native)\n")
            (write-text
             (string-append support "/provider-build.ss")
             ";;; -*- Gerbil -*-\n(import :std/build-script)\n(defbuild-script '((gxc: \"src/runtime/provider\")\n                   (exe: \"src/provider-server\"\n                         bin: \"provider\")))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings)))
              (check matching => []))))
    (test-case "agent policy rejects hardcoded runtime cache version identity"
          (let* ((root ".run/policy-build-runtime-cache-version-literal")
                 (src (string-append root "/src"))
                 (commands (string-append src "/commands")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir commands)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-cache-version-literal)\n")
            (write-text
             (string-append commands "/check-cache.ss")
             ";;; -*- Gerbil -*-\n(import :asp-gerbil-scheme/src/constants)\n(def +check-cache-format-version+ \"cache-format.v1\")\n(def +check-cache-version+ \"provider-cache.v1\")\n(def (check-cache-state)\n  [version: +check-cache-version+\n   formatVersion: +check-cache-format-version+\n   releaseVersion: +release-version+])\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter (lambda (finding)
                              (equal? (hash-get (type-finding-details finding)
                                                'kind)
                                      "build-runtime-cache-version-release-drift"))
                            (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                         findings)))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (type-finding-path finding)
                     => "src/commands/check-cache.ss")
              (check (type-finding-selector finding)
                     => "src/commands/check-cache.ss:4-4")
              (check (hash-get details 'bindingName)
                     => "+check-cache-version+")
              (check (hash-get details 'valueType) => "string"))))
    (test-case "agent policy accepts release-derived runtime cache version identity"
          (let* ((root ".run/policy-build-runtime-cache-version-derived")
                 (src (string-append root "/src"))
                 (commands (string-append src "/commands")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir commands)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-cache-version-derived)\n")
            (write-text
             (string-append commands "/check-cache.ss")
             ";;; -*- Gerbil -*-\n(import :asp-gerbil-scheme/src/constants)\n(def +check-cache-format-version+ \"cache-format.v1\")\n(def +check-cache-version+ +release-version+)\n(def (check-cache-state)\n  [version: +check-cache-version+\n   formatVersion: +check-cache-format-version+\n   releaseVersion: +release-version+])\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter (lambda (finding)
                              (equal? (hash-get (type-finding-details finding)
                                                'kind)
                                      "build-runtime-cache-version-release-drift"))
                            (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                         findings))))
              (check matching => []))))
    ))

;; PolicyTest
(def agent-build-package-rejection-policy-test
  (test-suite "gerbil scheme harness package build rejection policy"
    (test-case "agent policy rejects package build custom build systems"
           (let ((root ".run/policy-package-build-custom-system"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-custom-system)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import (only-in :std/misc/process run-process))\n(def (compile-all!)\n  (run-process [\"gxc\" \"-static\" \"src/main.ss\"])\n  (run-process [\"gsc\" \"-exe\" \"src/main.scm\"]))\n(def (main . args)\n  (compile-all!))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (groups (hash-get details 'evidenceGroups)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'kind)
                     => "package-build-custom-system")
              (check (hash-get details 'detectionCombiner)
                     => "package-build-custom-system-all-of")
              (check (hash-get details 'requiredGroups)
                     => ["package-build-file"
                         "missing-native-build-surface"
                         "manual-build-orchestration"])
              (check (not (not (member "package-build-file" groups)))
                     => #t)
              (check (not (not (member "missing-native-build-surface" groups)))
                     => #t)
               (check (not (not (member "manual-build-orchestration" groups)))
                      => #t))))
    (test-case "agent policy accepts shell processes that do not own compilation"
          (let ((root ".run/policy-package-build-ordinary-shell-process"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-ordinary-shell-process)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :std/build-script\n        (only-in :std/misc/process run-process))\n(defbuild-script '((gxc: \"src/library\")))\n(def (copy-docs!)\n  (run-process [\"sh\" \"-c\" \"cp README.org dist/README.org\"]))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index)))
              (check (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings)
                     => [])
              (check (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings)
                     => []))))
    (test-case "agent policy rejects package build framework overreach"
          (let ((root "t/scenarios/policy/package-build-framework-overreach/input"))
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (build-runtime-matching
                    (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (canonical-matching
                    (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (overreach-matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding)
                                         'kind)
                               "package-build-framework-overreach"))
                     build-runtime-matching))
                   (finding (car overreach-matching))
                   (details (type-finding-details finding))
                   (groups (hash-get details 'evidenceGroups)))
              (check canonical-matching => [])
              (check (length overreach-matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'detectionCombiner)
                     => "package-build-framework-overreach-all-of")
              (check (hash-get details 'requiredGroups)
                     => ["package-build-file"
                         "native-build-surface"
                         "local-build-state-owner"])
              (check (not (not (member "package-build-file" groups)))
                     => #t)
              (check (not (not (member "native-build-surface" groups)))
                     => #t)
              (check (not (not (member "local-build-state-owner" groups)))
                     => #t))))
    (test-case "agent policy rejects package build worker scheduler overreach"
          (let ((root ".run/policy-package-build-worker-overreach"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-worker-overreach)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :std/make\n        :clan/building)\n(def +package-build-worker-count+ 8)\n(def (spec)\n  (all-gerbil-modules))\n(%set-build-environment!\n \"build.ss\"\n name: \"sample\"\n deps: '()\n spec: spec)\n(def (package-build-job-queue modules)\n  modules)\n(def (package-build-run-worker! module options)\n  (apply make [module] options))\n(def (compile-package! options)\n  (for-each (lambda (module)\n              (package-build-run-worker! module options))\n            (package-build-job-queue (spec)))\n  (apply make (spec) options))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (build-runtime-matching
                    (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (canonical-matching
                    (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (overreach-matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding)
                                         'kind)
                               "package-build-framework-overreach"))
                     build-runtime-matching))
                   (finding (car overreach-matching))
                   (details (type-finding-details finding))
                   (groups (hash-get details 'evidenceGroups)))
              (check canonical-matching => [])
              (check (length overreach-matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'detectionCombiner)
                     => "package-build-framework-overreach-all-of")
              (check (hash-get details 'requiredGroups)
                     => ["package-build-file"
                         "native-build-surface"
                         "local-build-state-owner"])
              (check (not (not (member "package-build-file" groups)))
                     => #t)
              (check (not (not (member "native-build-surface" groups)))
                     => #t)
              (check (not (not (member "local-build-state-owner" groups)))
                     => #t))))
    (test-case "agent policy rejects manual compilation without a native build spec"
          (let ((root ".run/policy-package-build-canonical-shape"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-canonical-shape)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :std/make\n        (only-in :std/misc/process invoke))\n(def (compile-all!)\n  (setenv \"GERBIL_LOADPATH\" \"src:t\")\n  (make [\"src/main\"] srcdir: (current-directory))\n  (invoke \"gxc\" [\"-exe\" \"-o\" \".build/sample\" \"src/main.ss\"]))\n(def (main . args)\n  (compile-all!))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'kind)
                     => "package-build-canonical-shape")
              (check (hash-get details 'nativeBuildImport) => ":std/make")
              (check (hash-get details 'legacyBuildImport) => #f)
              (check (hash-get details 'buildSpecEntrypoint) => "make")
              (check (hash-get details 'moduleEnumerator) => #f)
              (check (hash-get details 'providerBuildInclude) => #f)
              (check (hash-get details 'manualEnvironmentSetup) => "setenv")
              (check (hash-get details 'manualCompilerDispatch) => "invoke")
              (check (hash-get details 'compositionalBuildShape)
                     => "use clan/building for harness source discovery/load path, std/build-script for simple gxpkg packages, or std/make for build-spec features such as ssi:/gsc:; keep package tests on Gerbil's gxtest runner and runtime commands in compiled modules")
              (check (hash-get details 'downstreamRepairPattern)
                     => "keep build.ss as the package build control plane, route package compilation through clan/building, std/build-script, or std/make build-spec, and keep provider behavior in a thin entry module over POO-native runtime owners"))))
    (test-case "agent policy accepts std/build-script package build"
          (let ((root ".run/policy-package-build-canonical-defbuild"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-canonical-defbuild)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import (only-in :std/build-script defbuild-script))\n(defbuild-script\n  '((exe: \"src/main\")))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index)))
              (check (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings)
                     => [])
              (check (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings)
                     => []))))
    (test-case "agent policy rejects apply make srcdir package build"
          (let ((root ".run/policy-package-build-canonical-apply-make"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-canonical-apply-make)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :std/make)\n(def (provider-build-spec)\n  '(\"src/main\"))\n(def (build-keys)\n  [debug: #f])\n(def (make-provider! options)\n  (apply make (provider-build-spec) srcdir: (current-directory) (append options (build-keys))))\n(def (compile-fast!)\n  (invoke \"gxc\" [\"-exe\" \"src/main.ss\"]))\n(def (main . args)\n  (make-provider! []))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'nativeBuildImport) => ":std/make")
              (check (hash-get details 'manualEnvironmentSetup) => #f)
              (check (hash-get details 'manualCompilerDispatch) => "invoke")))))
)

;; PolicyTest
(def agent-build-policy-test
  (test-suite "gerbil scheme harness agent build policy"
    (test-case "agent-build-runtime-policy-test"
      (check (run-test-suite! agent-build-runtime-policy-test) => #t))
    (test-case "agent-build-package-rejection-policy-test"
      (check (run-test-suite! agent-build-package-rejection-policy-test) => #t))
    (test-case "agent-build-canonical-acceptance-policy-test"
      (check (run-test-suite! agent-build-canonical-acceptance-policy-test) => #t))))
