;;; -*- Gerbil -*-
;;; gerbil scheme harness agent build policy.

(import :gerbil/gambit
        :std/test
        :asp-gerbil-scheme/src/parser/facade
        :asp-gerbil-scheme/src/policy/facade
        :asp-gerbil-scheme/src/types/facade
        (only-in "./agent-build-canonical-acceptance-test"
                 agent-build-canonical-acceptance-policy-test)
        "./fixtures")
(export agent-build-policy-test)

;; PolicyTest
(def agent-build-runtime-policy-test
  (test-suite "gerbil scheme harness agent build runtime policy"
    (test-case "agent policy rejects package build CLI routing"
          (let ((root ".run/policy-package-build-routing"))
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-routing)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :clan/base)\n(def (write-wrapper out)\n  (display \"if [ \\\"${1:-}\\\" = search ] && [ \\\"${2:-}\\\" = pattern ]; then\\n\" out))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-019" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (type-finding-selector finding) => "build.ss:4-4")
              (check (hash-get (type-finding-details finding) 'kind)
                     => "package-build-responsibility"))))
    (test-case "agent policy rejects package build wrapper definitions"
          (let ((root ".run/policy-package-build-wrapper-definition"))
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-wrapper)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :clan/base)\n(def (write-native-link-wrapper build-prefix)\n  build-prefix)\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-019" findings))
                   (finding (car matching)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (type-finding-selector finding) => "build.ss:3-4")
              (check (hash-get (type-finding-details finding) 'kind)
                     => "package-build-wrapper-definition"))))
    (test-case "agent policy rejects build-runtime shell template regression"
          (let* ((root ".run/policy-build-runtime-shell-template")
                 (src (string-append root "/src"))
                 (support (string-append src "/build-api")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-quality)\n")
            (write-text
             (string-append support "/provider-cli.ss")
             ";;; -*- Gerbil -*-\n(def (shell-if condition body)\n  (string-append \"if [ \" condition \" ]; then\\n\" body \"\\nfi\\n\"))\n(def (shell-exec command)\n  (string-append \"exec \" command \" \\\"$@\\\"\\n\"))\n(def (write-wrapper out)\n  (display \"#!/bin/sh\\nset -eu\\n\" out)\n  (display \"find src -name '*.ss' -print | xargs gxc\\n\" out))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (groups (hash-get (type-finding-details finding)
                                     'evidenceGroups)))
              (check (length matching) => 1)
              (check (type-finding-path finding)
                     => "src/build-api/provider-cli.ss")
              (check (hash-get details 'detectionCombiner)
                     => "build-runtime-shell-template-composite")
              (check [(hash-get details 'detectionPrototype) (hash-get details 'detectionCombinerKind) (hash-get details 'detectionSourcePattern)]
                     => ["build-runtime-shell-template-composite" "threshold" "poo-prototype-composition"])
              (check (hash-get details 'detectionThreshold) => 2)
              (check (not (not (member "shell-helper-definitions" groups)))
                     => #t)
              (check (not (not (member "shell-control-literals" groups)))
                     => #t))))
    (test-case "agent policy requires multiple build-runtime evidence groups"
          (let* ((root ".run/policy-build-runtime-single-evidence")
                 (src (string-append root "/src"))
                 (support (string-append src "/build-api")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-single-evidence)\n")
            (write-text
             (string-append support "/provider-cli.ss")
             ";;; -*- Gerbil -*-\n(def (shell-if condition body)\n  [condition body])\n(def (shell-exec command)\n  [command])\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings)))
              (check matching => []))))
    (test-case "agent policy rejects compiler execution under a global lock"
          (let* ((root ".run/policy-build-runtime-global-lock-compile")
                 (src (string-append root "/src"))
                 (support (string-append src "/building")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-lock)\n")
            (write-text
             (string-append support "/scheduler.ss")
             ";;; -*- Gerbil -*-\n(def (compile-package! lock spec)\n  (with-lock lock\n    (lambda ()\n      (make spec))))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding) 'kind)
                               "build-runtime-global-lock-compile"))
                     (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                  findings)))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'caller) => "compile-package!")
              (check (hash-get details 'lockCallee) => "with-lock")
              (check (hash-get details 'compileCallee) => "make"))))
    (test-case "agent policy accepts a short state lock before compilation"
          (let* ((root ".run/policy-build-runtime-short-lock")
                 (src (string-append root "/src"))
                 (support (string-append src "/building")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-short-lock)\n")
            (write-text
             (string-append support "/scheduler.ss")
             ";;; -*- Gerbil -*-\n(def (transition-ready! lock table)\n  (with-lock lock (lambda () (hash-put! table 'ready #t))))\n(def (compile-package! spec)\n  (make spec))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding) 'kind)
                               "build-runtime-global-lock-compile"))
                     (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                  findings))))
              (check matching => []))))
    (test-case "agent policy rejects a serializing shadow module scheduler"
          (let* ((root ".run/policy-build-runtime-shadow-scheduler")
                 (src (string-append root "/src"))
                 (support (string-append src "/building")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-shadow-scheduler)\n")
            (write-text
             (string-append support "/scheduler.ss")
             ";;; -*- Gerbil -*-\n(def (import/mx lock module)\n  (with-lock lock (lambda () (import-module module))))\n(def (wait-for dependency)\n  (completion-wait! dependency))\n(def (coordinate! lock module dependency work)\n  (wait-for dependency)\n  (channel-put work (import/mx lock module)))\n(def (run-scheduler!)\n  (let (work (make-channel))\n    (channel-close work)))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding) 'kind)
                               "build-runtime-shadow-scheduler"))
                     (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                  findings)))
                   (details (type-finding-details (car matching))))
              (check (length matching) => 1)
              (check (string? (hash-get details 'lockSelector)) => #t)
              (check (string? (hash-get details 'dependencyWaitSelector)) => #t)
              (check (string? (hash-get details 'workChannelSelector)) => #t))))
    (test-case "agent policy rejects direct native provider gxc executable compile"
          (let* ((root ".run/policy-build-runtime-direct-native-gxc")
                 (src (string-append root "/src"))
                 (support (string-append src "/build-api")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-direct-native-gxc)\n")
            (write-text
             (string-append support "/provider-build.ss")
             ";;; -*- Gerbil -*-\n(def (compile-native-fast-binary! name source)\n  (let ((tmp-binary (string-append name \".native-tmp\")))\n    (invoke \"gxc\" [\"-exe\" \"-o\" tmp-binary source])\n    (invoke \"mv\" [tmp-binary name])))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (groups (hash-get details 'evidenceGroups)))
              (check (length matching) => 1)
              (check (type-finding-path finding)
                     => "src/build-api/provider-build.ss")
              (check (hash-get details 'kind)
                     => "build-runtime-native-compile-safety")
              (check (hash-get details 'detectionCombiner)
                     => "build-runtime-native-compile-safety-all-of")
              (check (hash-get details 'requiredGroups)
                     => ["native-provider-compile-owner"
                         "direct-native-exe-dispatch"
                         "missing-native-link-wrapper"])
              (check (not (not (member "native-provider-compile-owner" groups)))
                     => #t)
              (check (not (not (member "direct-native-exe-dispatch" groups)))
                     => #t)
              (check (not (not (member "missing-native-link-wrapper" groups)))
                     => #t))))
    (test-case "agent policy accepts timeout-safe native provider wrapper delegation"
          (let* ((root ".run/policy-build-runtime-native-wrapper-delegation")
                 (src (string-append root "/src"))
                 (support (string-append src "/build-api")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir support)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-native-wrapper-delegation)\n")
            (write-text
             (string-append support "/provider-build.ss")
             ";;; -*- Gerbil -*-\n(def (compile-build-runtime-executable! name source)\n  [name source])\n(def (compile-native-fast-binary! name source)\n  (invoke (compile-build-runtime-executable!\n           \"gerbil-native-link\"\n           \"src/build-api/native-wrapper-runtime.ss\")\n          [(string-append name \".native-tmp\") name source]))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings)))
              (check matching => []))))
    (test-case "agent policy rejects hardcoded runtime cache version identity"
          (let* ((root ".run/policy-build-runtime-cache-version-literal")
                 (src (string-append root "/src"))
                 (commands (string-append src "/commands")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir commands)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-cache-version-literal)\n")
            (write-text
             (string-append commands "/check-cache.ss")
             ";;; -*- Gerbil -*-\n(import :asp-gerbil-scheme/src/constants)\n(def +check-cache-format-version+ \"cache-format.v1\")\n(def +check-cache-version+ \"provider-cache.v1\")\n(def (check-cache-state)\n  [version: +check-cache-version+\n   formatVersion: +check-cache-format-version+\n   releaseVersion: +release-version+])\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter (lambda (finding)
                              (equal? (hash-get (type-finding-details finding)
                                                'kind)
                                      "build-runtime-cache-version-release-drift"))
                            (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                         findings)))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (type-finding-path finding)
                     => "src/commands/check-cache.ss")
              (check (type-finding-selector finding)
                     => "src/commands/check-cache.ss:4-4")
              (check (hash-get details 'bindingName)
                     => "+check-cache-version+")
              (check (hash-get details 'valueType) => "string"))))
    (test-case "agent policy accepts release-derived runtime cache version identity"
          (let* ((root ".run/policy-build-runtime-cache-version-derived")
                 (src (string-append root "/src"))
                 (commands (string-append src "/commands")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir src)
            (ensure-dir commands)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-runtime-cache-version-derived)\n")
            (write-text
             (string-append commands "/check-cache.ss")
             ";;; -*- Gerbil -*-\n(import :asp-gerbil-scheme/src/constants)\n(def +check-cache-format-version+ \"cache-format.v1\")\n(def +check-cache-version+ +release-version+)\n(def (check-cache-state)\n  [version: +check-cache-version+\n   formatVersion: +check-cache-format-version+\n   releaseVersion: +release-version+])\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching
                    (filter (lambda (finding)
                              (equal? (hash-get (type-finding-details finding)
                                                'kind)
                                      "build-runtime-cache-version-release-drift"))
                            (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020"
                                         findings))))
              (check matching => []))))
    (test-case "agent policy rejects native-fast imports of full command adapters"
          (let* ((root ".run/policy-native-fast-command-adapter")
                 (fast (string-append root "/src/check-fast")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir (string-append root "/src"))
            (ensure-dir fast)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/native-fast-command-adapter)\n")
            (write-text
             (string-append fast "/gerbil-scheme-check.ss")
             ";;; -*- Gerbil -*-\n(import :commands/check)\n(export main)\n(def (main . args)\n  (check-main args))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (groups (hash-get details 'evidenceGroups)))
              (check (length matching) => 1)
              (check (type-finding-path finding)
                     => "src/check-fast/gerbil-scheme-check.ss")
              (check (hash-get details 'kind)
                     => "build-runtime-native-fast-command-adapter")
              (check (hash-get details 'detectionCombiner)
                     => "native-fast-command-adapter-all-of")
              (check (hash-get details 'requiredGroups)
                     => ["native-fast-source" "full-command-adapter-import"])
              (check (not (not (member "native-fast-source" groups)))
                     => #t)
              (check (not (not (member "full-command-adapter-import" groups)))
                     => #t))))
    (test-case "agent policy accepts dependency-light native-fast source"
          (let* ((root ".run/policy-native-fast-lightweight")
                 (fast (string-append root "/src/search-fast")))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (ensure-dir (string-append root "/src"))
            (ensure-dir fast)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/native-fast-lightweight)\n")
            (write-text
             (string-append fast "/gerbil-scheme-search-extension.ss")
             ";;; -*- Gerbil -*-\n(import :gerbil/gambit)\n(export main)\n(def (main . args)\n  (display \"ok\\n\")\n  0)\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings)))
              (check matching => [])))))
)

;; PolicyTest
(def agent-build-package-rejection-policy-test
  (test-suite "gerbil scheme harness package build rejection policy"
    (test-case "agent policy rejects package build shell pipelines"
          (let ((root ".run/policy-package-build-shell-pipeline"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-shell-pipeline)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(def (refresh!)\n  (invoke \"sh\" [\"-c\" \"find src -name '*.ss' -print | xargs gxc -static\"])\n  #t)\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (shell-matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding)
                                         'detectionCombiner)
                               "package-build-shell-pipeline-all-of"))
                     matching))
                   (finding (car shell-matching))
                   (details (type-finding-details finding))
                   (groups (hash-get (type-finding-details finding)
                                     'evidenceGroups)))
              (check (length shell-matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'detectionCombiner)
                     => "package-build-shell-pipeline-all-of")
              (check [(hash-get details 'detectionPrototype) (hash-get details 'detectionCombinerKind) (hash-get details 'detectionSourcePattern)]
                     => ["package-build-shell-pipeline-all-of" "all-of" "poo-prototype-composition"])
              (check (hash-get details 'requiredGroups)
                     => ["shell-dispatch-call" "shell-pipeline-literal"])
              (check (not (not (member "shell-dispatch-call" groups)))
                     => #t)
              (check (not (not (member "shell-pipeline-literal" groups)))
                     => #t))))
     (test-case "agent policy rejects package build custom build systems"
           (let ((root ".run/policy-package-build-custom-system"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-custom-system)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import (only-in :std/misc/process run-process))\n(def (compile-all!)\n  (run-process [\"gxc\" \"-static\" \"src/main.ss\"])\n  (run-process [\"gsc\" \"-exe\" \"src/main.scm\"]))\n(def (main . args)\n  (compile-all!))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (finding (car matching))
                   (details (type-finding-details finding))
                   (groups (hash-get details 'evidenceGroups)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'kind)
                     => "package-build-custom-system")
              (check (hash-get details 'detectionCombiner)
                     => "package-build-custom-system-all-of")
              (check (hash-get details 'requiredGroups)
                     => ["package-build-file"
                         "missing-clan-build-environment"
                         "manual-build-orchestration"])
              (check (not (not (member "package-build-file" groups)))
                     => #t)
              (check (not (not (member "missing-clan-build-environment" groups)))
                     => #t)
               (check (not (not (member "manual-build-orchestration" groups)))
                      => #t))))
    (test-case "agent policy rejects package build framework overreach"
          (let ((root "t/scenarios/policy/package-build-framework-overreach/input"))
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (build-runtime-matching
                    (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (canonical-matching
                    (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (overreach-matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding)
                                         'kind)
                               "package-build-framework-overreach"))
                     build-runtime-matching))
                   (finding (car overreach-matching))
                   (details (type-finding-details finding))
                   (groups (hash-get details 'evidenceGroups)))
              (check canonical-matching => [])
              (check (length overreach-matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'detectionCombiner)
                     => "package-build-framework-overreach-all-of")
              (check (hash-get details 'requiredGroups)
                     => ["package-build-file"
                         "native-build-surface"
                         "local-build-state-owner"])
              (check (not (not (member "package-build-file" groups)))
                     => #t)
              (check (not (not (member "native-build-surface" groups)))
                     => #t)
              (check (not (not (member "local-build-state-owner" groups)))
                     => #t))))
    (test-case "agent policy rejects package build worker scheduler overreach"
          (let ((root ".run/policy-package-build-worker-overreach"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-worker-overreach)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :std/make\n        :clan/building)\n(def +package-build-worker-count+ 8)\n(def (spec)\n  (all-gerbil-modules))\n(%set-build-environment!\n \"build.ss\"\n name: \"sample\"\n deps: '()\n spec: spec)\n(def (package-build-job-queue modules)\n  modules)\n(def (package-build-run-worker! module options)\n  (apply make [module] options))\n(def (compile-package! options)\n  (for-each (lambda (module)\n              (package-build-run-worker! module options))\n            (package-build-job-queue (spec)))\n  (apply make (spec) options))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (build-runtime-matching
                    (filter-rule "GERBIL-SCHEME-AGENT-POLICY-020" findings))
                   (canonical-matching
                    (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (overreach-matching
                    (filter
                     (lambda (finding)
                       (equal? (hash-get (type-finding-details finding)
                                         'kind)
                               "package-build-framework-overreach"))
                     build-runtime-matching))
                   (finding (car overreach-matching))
                   (details (type-finding-details finding))
                   (groups (hash-get details 'evidenceGroups)))
              (check canonical-matching => [])
              (check (length overreach-matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'detectionCombiner)
                     => "package-build-framework-overreach-all-of")
              (check (hash-get details 'requiredGroups)
                     => ["package-build-file"
                         "native-build-surface"
                         "local-build-state-owner"])
              (check (not (not (member "package-build-file" groups)))
                     => #t)
              (check (not (not (member "native-build-surface" groups)))
                     => #t)
              (check (not (not (member "local-build-state-owner" groups)))
                     => #t))))
    (test-case "agent policy rejects package build without clan/building surface"
          (let ((root ".run/policy-package-build-canonical-shape"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-canonical-shape)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :std/make\n        (only-in :std/misc/process invoke))\n(def (compile-all!)\n  (setenv \"GERBIL_LOADPATH\" \"src:t\")\n  (make [\"src/main\"] srcdir: (current-directory))\n  (invoke \"gxc\" [\"-exe\" \"-o\" \".build/sample\" \"src/main.ss\"]))\n(def (main . args)\n  (compile-all!))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (type-finding-path finding) => "build.ss")
              (check (hash-get details 'kind)
                     => "package-build-canonical-shape")
              (check (hash-get details 'nativeBuildImport) => #f)
              (check (hash-get details 'legacyBuildImport) => ":std/make")
              (check (hash-get details 'buildSpecEntrypoint) => #f)
              (check (hash-get details 'moduleEnumerator) => #f)
              (check (hash-get details 'providerBuildInclude) => #f)
              (check (hash-get details 'manualEnvironmentSetup) => "make")
              (check (hash-get details 'manualCompilerDispatch) => "invoke")
              (check (hash-get details 'compositionalBuildShape)
                     => "use clan/building for source discovery/load path, keep package tests on Gerbil's gxtest runner, and call provider CLI commands through the compiled package module")
              (check (hash-get details 'downstreamRepairPattern)
                     => "keep build.ss as the package build control plane, route package compilation through clan/building, and keep command/runtime behavior in src/cli and src/commands"))))
    (test-case "agent policy rejects legacy defbuild-script package build"
          (let ((root ".run/policy-package-build-canonical-defbuild"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-canonical-defbuild)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import (only-in :std/build-script defbuild-script))\n(defbuild-script\n  '((exe: \"src/main\")))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'legacyBuildImport)
                     => ":std/build-script")
              (check (hash-get details 'buildSpecEntrypoint) => #f))))
    (test-case "agent policy rejects apply make srcdir package build"
          (let ((root ".run/policy-package-build-canonical-apply-make"))
            (reset-fixture-root root)
            (ensure-dir ".run")
            (ensure-dir root)
            (write-text (string-append root "/gerbil.pkg")
                        "(package: sample/build-canonical-apply-make)\n")
            (write-text
             (string-append root "/build.ss")
             ";;; -*- Gerbil -*-\n(import :std/make)\n(def (provider-build-spec)\n  '(\"src/main\"))\n(def (build-keys)\n  [debug: #f])\n(def (make-provider! options)\n  (apply make (provider-build-spec) srcdir: (current-directory) (append options (build-keys))))\n(def (compile-fast!)\n  (invoke \"gxc\" [\"-exe\" \"src/main.ss\"]))\n(def (main . args)\n  (make-provider! []))\n")
            (let* ((index (collect-project root))
                   (findings (run-agent-policy index))
                   (matching (filter-rule "GERBIL-SCHEME-AGENT-POLICY-025" findings))
                   (finding (car matching))
                   (details (type-finding-details finding)))
              (check (length matching) => 1)
              (check (hash-get details 'legacyBuildImport) => ":std/make")
              (check (hash-get details 'manualEnvironmentSetup) => "apply")))))
)

;; PolicyTest
(def agent-build-policy-test
  (test-suite "gerbil scheme harness agent build policy"
    agent-build-runtime-policy-test
    agent-build-package-rejection-policy-test
    agent-build-canonical-acceptance-policy-test))
